# addonDir - location of the ESO addon directory
addonDir = "/home/jah/Documents/Elder Scrolls Online/live/AddOns"

# addons - List of addons to be installed
#   name - Name of the addon
#   url - Download URL of the addon, it is the link under the Download button on ESOUI.
#   dependency - (default: false) Determines, if the addon is a dependency.
#                Set this to true, if you don't use the addon standalone, but only as a dependency for another addon.
[[addons]]
name = "SkyShards"
url = "https://www.esoui.com/downloads/download128-SkyShards.html"

[[addons]]
name = "CustomCompassPins"
url = "https://www.esoui.com/downloads/download185-CustomCompassPins.html"
dependency = true

[[addons]]
name = "LibAddonMenu-2.0"
url = "https://www.esoui.com/downloads/download7-LibAddonMenu.html"
dependency = true

[[addons]]
name = "LibGPS"
url = "https://www.esoui.com/downloads/download601-LibGPS2.html"
dependency = true

[[addons]]
name = "LibMapPing"
url = "https://www.esoui.com/downloads/download1302-LibMapPing.html"
dependency = true

[[addons]]
name = "LibMapPins-1.0"
url = "https://www.esoui.com/downloads/download563-LibMapPins.html"
dependency = true

[[addons]]
name = "LibChatMessage"
url = "https://www.esoui.com/downloads/download2382-LibChatMessage.html"
dependency = true

[[addons]]
name = "LibDebugLogger"
url = "https://www.esoui.com/downloads/download2275-LibDebugLogger.html"
dependency = true

[[addons]]
name = "TamrielTradeCentre"
url = "https://www.esoui.com/downloads/download1245-TamrielTradeCentre.html"

[[addons]]
name = "LibCustomMenu"
url = "https://www.esoui.com/downloads/landing.php?s=7c86aae6e6879a204910b66d8a22d3a0&fileid=1146"
dependency = true

[[addons]]
name = "PriceTooltip"
url = "https://www.esoui.com/downloads/landing.php?s=7c86aae6e6879a204910b66d8a22d3a0&fileid=2221"

#[[addons]]
#name = "KelaPadUI"
#url = "https://www.esoui.com/downloads/landing.php?s=c282436de28fe08473cbc6177fb4e9c2&fileid=2740"

[[addons]]
name = "LibSets"
url = "https://www.esoui.com/downloads/landing.php?s=c282436de28fe08473cbc6177fb4e9c2&fileid=2241"
dependency = true

[[addons]]
name = "LibItemLink"
url = "https://www.esoui.com/downloads/landing.php?s=c282436de28fe08473cbc6177fb4e9c2&fileid=2423"
dependency = true

[[addons]]
name = "UndauntedPledgesUtilities"
url = "https://www.esoui.com/downloads/landing.php?s=c282436de28fe08473cbc6177fb4e9c2&fileid=2267"

[[addons]]
name = "LibSlashCommander"
url = "https://www.esoui.com/downloads/landing.php?s=c282436de28fe08473cbc6177fb4e9c2&fileid=1508"
dependency = true

[[addons]]
name = "CShortcutPieMenu"
url = "https://www.esoui.com/downloads/landing.php?s=7895645e2abdfab0e372f62788f88112&fileid=3088"

[[addons]]
name = "DolgubonsLazyWritCreator"
url = "https://www.esoui.com/downloads/landing.php?s=7895645e2abdfab0e372f62788f88112&fileid=1346"

[[addons]]
name = "LibLazyCrafting"
url = "https://www.esoui.com/downloads/landing.php?s=7895645e2abdfab0e372f62788f88112&fileid=1594"
dependency = true

[[addons]]
name = "VotansKeybinder"
url = "https://www.esoui.com/downloads/landing.php?s=75cf924e820075aab9ef44d3d28b391b&fileid=1174"

[[addons]]
name = "libAddonKeybinds"
url = "https://www.esoui.com/downloads/landing.php?s=75cf924e820075aab9ef44d3d28b391b&fileid=1253"
dependency = true

[[addons]]
name = "LibSavedVars"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2161"
dependency = true

[[addons]]
name = "LibFoodDrinkBuff"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1902"
dependency = true

[[addons]]
name = "TEB"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3075"

[[addons]]
name = "MapPins"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1881"

#[[addons]]
#name = "ArkadiusTradeTools"
#url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1752"

[[addons]]
name = "VotansMiniMap"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1399"

[[addons]]
name = "LibAsync"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2125"
dependency = true

[[addons]]
name = "LibHarvensAddonSettings"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=584"
dependency = true

[[addons]]
name = "BeamMeUp"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2143"

[[addons]]
name = "LibDialog"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1931"
dependency = true

[[addons]]
name = "LibMapPing"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1302"
dependency = true

[[addons]]
name = "LibDebugLogger"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2275"
dependency = true

[[addons]]
name = "LibZone"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2171"
dependency = true

[[addons]]
name = "AltAttributes"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3056"

[[addons]]
name = "IsJustaDIWM"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3136"

[[addons]]
name = "libAddonKeybinds"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1253"
dependency = true

[[addons]]
name = "VotansKeybinder"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1174"

[[addons]]
name = "LibChatMessage"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2382"
dependency = true

[[addons]]
name = "LibGPS"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=601"
dependency = true

[[addons]]
name = "LibMapPins-1.0"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=563"
dependency = true

[[addons]]
name = "CustomCompassPins"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=185"
dependency = true

[[addons]]
name = "LoreBooks"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=288"

[[addons]]
name = "FishermansFriend"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2904"

[[addons]]
name = "LibPrice"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=2204"
dependency = true

[[addons]]
name = "LibCharacterKnowledge"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3317"
dependency = true

[[addons]]
name = "WritWorthy"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=1605"

[[addons]]
name = "LibMediaProvider-1.0"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=56"
dependency = true

[[addons]]
name = "MailBuddy"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=866"

[[addons]]
name = "GamePadHelper"
url = "https://esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3268"

[[addons]]
name = "LibCovetousCountess"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3266"
dependency = true

[[addons]]
name = "LibMultiIcon"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3267"
dependency = true

[[addons]]
name = "LibTraitResearch"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3264"
dependency = true

[[addons]]
name = "LibItemLinkDecoder"
url = "https://www.esoui.com/downloads/landing.php?s=82766347ca89038570b49eec59091d46&fileid=3265"
dependency = true

